### ISSUE TITLE
System.Exception: FMOD Failed: ERR_INTERNAL on Launch

### ISSUE THREAD

**Issue by TheDrunkenBeard** [NoelFB/Celeste#13]
Issues with the Sound Blaster AE-5 audio card, launching the game under any other audio device works fine except that particular card.

Celeste Error Log
==========================================

Ver 1.2.3.2
6/24/2018 12:33:53 AM
System.Exception: FMOD Failed: ERR_INTERNAL
   at Celeste.Audio.CheckFmod(RESULT result)
   at Celeste.Audio.Init()
   at Celeste.GameLoader.LoadThread()
   at Celeste.RunThread.RunThreadWithLogging(Action method)

==========================================

Sound BlasterX AE-5
Driver Version: 6.0.105.18

**Comment by TheDrunkenBeard** [comment]
I was able to resolve the issue, my sound card supports 32bit audio which what ever audio platform you are using doesn't.

Bumping my sound card to 24bit audio has resolved the issue.

Thanks,
