### ISSUE TITLE
Incompatibility with Reshade

### ISSUE THREAD

**Issue by HowlHighwind** [NoelFB/Celeste#18]
Hi, I know this is not actually a Celeste bug (or maybe it is)

But, well, Since The XNA (DX) version of the game not even hooks with this "post-processing inyector".

I just like to understand a bit better why the FNA (OGL) straight right crashes. More exactly trowing a
>Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: OpenGL 2.1 support is required!
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.LoadGLEntryPoints()
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters, GraphicsAdapter adapter)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters presentationParameters, GraphicsAdapter adapter)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.get_GraphicsDevice()
   at Microsoft.Xna.Framework.Game.InitializeGraphicsService()
   at Microsoft.Xna.Framework.Game.get_GraphicsDevice()
   at Celeste.Settings.get_MaxScale()
   at Celeste.Settings.AfterLoad()
   at Celeste.Celeste..ctor()
   at Celeste.Celeste.Main(String[] args)
There seems to be a problem with the OpenGL32.dll that is required for the hook of ReShade to work.
I tried with various dlls from around the web with various degrees of success but at the end no one work property.

I do not rule out the possibility that maybe AMD and their OpenGL's ~sketchy~ support are at fault here.
If that was the case this is maybe helpful

` R5 2600x RX 580 W10(1809)`
**Radeon software version: 18.12.3**

I basically try asking here since crosire is not exactly helpful ~like at all~ (and not very open to fix things for other people)
*That said I asking here out of ignorance, since I not exactly knowledgeable about any of this, as you can **clearly** tell*

I tried, don't kill me.
:^)

**Comment by HowlHighwind** [comment]
Seems like I didn't do enough testing.
I can confirm that Celeste works as expected with dxgi.dll (DX11 32)
I assume that's what's fall back into or It's some sort of incompatibility with the wrapper.
But again, I'm not sure and I'm not that savvy about how this works.
I'm still curious to know what's wrong here but I'm probably taking precious time of someone, with my nonsense ramblings of things no one cares about.
So that's it, have a great day ❤️
